// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"owntracks_server/internal/conf"
)

// Injectors from wire.go:

// InitializeWeb 组装 Web 控制台依赖并运行（阻塞至退出）。
func InitializeWeb(cfg *conf.WebConfig, logPath string) (struct{}, error) {
	loggerBundle, err := ProvideLogger(logPath)
	if err != nil {
		return struct{}{}, err
	}
	v, err := RunWeb(cfg, loggerBundle)
	if err != nil {
		return struct{}{}, err
	}
	return v, nil
}
